#include "SkyboxRenderer.h"
#include "../Textures/TextureManager.h"

namespace Pressure {

	const std::vector<float> SkyboxRenderer::VERTICES = {
		-PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE,
		-PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE,
		PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE,
		PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE,
		PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE,
		-PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE,

		-PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE,
		-PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE,
		-PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE,
		-PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE,
		-PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE,
		-PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE,

		PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE,
		PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE,
		PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE,
		PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE,
		PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE,
		PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE,

		-PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE,
		-PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE,
		PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE,
		PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE,
		PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE,
		-PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE,

		-PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE,
		PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE,
		PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE,
		PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE,
		-PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE,
		-PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE,

		-PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE,
		-PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE,
		PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE,
		PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE,
		-PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE,
		PRESSURE_SKYBOX_SIZE, -PRESSURE_SKYBOX_SIZE, PRESSURE_SKYBOX_SIZE
	};

	SkyboxRenderer::SkyboxRenderer(Loader& loader, GLFWwindow* window) : window(window) {
		cube = loader.loadToVao(VERTICES, 3);
		texture = loader.loadCubeMap(PRESSURE_SKYBOX_FILE);
		updateProjectionMatrix();
	}

	void SkyboxRenderer::updateProjectionMatrix() {
		shader.start();
		shader.loadProjectionMatrix(Matrix4f().createProjectionMatrix(window));
		shader.stop();
	}

	void SkyboxRenderer::render(Camera& camera) {
		shader.start();
		shader.loadViewMatrix(camera);
		glBindVertexArray(cube->getVaoID());
		glEnableVertexAttribArray(0);
		glActiveTexture(GL_TEXTURE0);
		TextureManager::Inst()->BindTexture(texture, GL_TEXTURE_CUBE_MAP);
		glTexParameteri(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
		glTexParameteri(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
		glTexParameteri(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_WRAP_R, GL_CLAMP_TO_EDGE);
		glTexParameteri(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
		glTexParameteri(GL_TEXTURE_CUBE_MAP, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
		glDrawArrays(GL_TRIANGLES, 0, cube->getVertexCount());
		glDisableVertexAttribArray(0);
		glBindVertexArray(0);
		shader.stop();
	}

}